In [4]:
import numpy as np

''' made by BJH '''
def dfs(graph, start):
    result, visit = [], []
    visit.append(start)

    while visit:
        node = visit.pop()
        if node not in result:
            try:
                result.append(node)
                visit.extend(graph[node])
            except:
                return node

    return result

def two_pass_labeling(image):
    label = 0
    labels = np.zeros_like(image)
    equivalences = dict()

    # First Pass
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            if image[i, j] != 0:  # Object Pixel
                neighbors = []

                # 인접 픽셀 확인
                if i > 0 and labels[i-1, j] > 0:
                    neighbors.append(labels[i-1, j])
                if j > 0 and labels[i, j-1] > 0:
                    neighbors.append(labels[i, j-1])

                # 인접한 픽셀의 레이블이 서로 다를 경우, 레이블 값이 작은 수를 선택
                if neighbors:
                    min_neighbor = min(neighbors)
                    labels[i, j] = min_neighbor

                    for neighbor in neighbors:
                        if neighbor != min_neighbor:
                            equivalences[neighbor] = [min_neighbor]
                else:
                    label += 1
                    labels[i, j] = label

    print(equivalences)
    print('first pass')
    print(labels, '\n')

    # Second Pass
    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            if labels[i, j] in equivalences:
                # labels[i, j] = equivalences[labels[i, j]][0]
                labels[i, j] = dfs(equivalences, labels[i, j])
    print('second pass')
    print(labels)


In [5]:
img = np.array([
        [0,0,0,0,0,0,0,0,0,0,0],
        [0,0,0,0,1,1,0,0,0,0,0],
        [0,0,0,1,1,0,0,0,0,1,0],
        [0,0,1,1,1,1,0,0,1,1,0],
        [0,1,1,1,1,0,0,1,1,1,0],
        [0,0,0,0,0,0,0,0,0,0,0]
    ])

In [6]:
two_pass_labeling(img)

{2: [1], 4: [2], 5: [3], 6: [4], 7: [5]}
first pass
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 2 1 0 0 0 0 3 0]
 [0 0 4 2 1 1 0 0 5 3 0]
 [0 6 4 2 1 0 0 7 5 3 0]
 [0 0 0 0 0 0 0 0 0 0 0]] 

second pass
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 3 0]
 [0 0 1 1 1 1 0 0 3 3 0]
 [0 1 1 1 1 0 0 3 3 3 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
